### ISSUE TITLE
外径入力

### ISSUE THREAD

**Issue by RyoNawa** [mshackers/pin-shaft-diameter-optimizer#3]
分数を入れられるようにできると嬉しい。将来の英語化とインチ圏対応のため。

**Comment by masaha03** [comment]
「外径入力」のインターフェイスについて、「分数を入力したい」と「インチ圏に対応したい」の間に違いはある？

**Comment by RyoNawa** [comment]
違いというか、今も単位は何にしても構わないようになってる。
インチ圏では寸法に小数の他に分数も使う、というだけ。

**Comment by masaha03** [comment]
インチ圏への対応については、分数入力以外に何もする必要はない、という理解でOK？

**Comment by RyoNawa** [comment]
okと思う。
