### ISSUE TITLE
結果表示の絵をやめる

### ISSUE THREAD

**Issue by RyoNawa** [mshackers/pin-shaft-diameter-optimizer#4]
結果表示絵はやっぱり不要だと思うので無しにしたい。間違ってるし。

**Comment by masaha03** [comment]
消すのはいいけど、どこが間違ってるのかできれば教えてほしい。

**Comment by RyoNawa** [comment]
すまんね。寸法が自動で反映されることは喜ばしいんだけど、間違ってるというのは図面としての書式です。
基本的にSVGの絵とほぼ同じ表現になってないと、技術者が見ると形状が読めないのですよ。
断面であることを示すハッチング（の角度は水平垂直でなく見やすければ何でもよい）
中心線の一点鎖線 回転対称形状を示す
輪切り断面に十字の一点鎖線で中心マーク
ハウジングの断面形状、輪切り断面のシャフトの断面形状が実物を切断したのと違う、とかね。

**Comment by masaha03** [comment]
そういうレベルの間違いね。了解。
数値の指示が間違ってるとかそういうレベルだと、開発に支障をきたす恐れがあるので。
あと、今後のための記録として「不要だと思う」理由も書いてほしい。
「間違ってる」は理由にならないので（直せばいいだけ）。

**Comment by RyoNawa** [comment]
絵自体がSVGとJSと内容かぶってるので、
ちゃんとした書式に作りこんでSVGの絵を消す or JSの絵を消す
の2択だと思われた。
+JSの絵でハッチングを入れるのは面倒そうに思えた。
というのが理由です。

**Comment by masaha03** [comment]
いや、それならJSでハッチングを入れるのが面倒かどうか聞こうよｗ
そもそもSVGがあれば十分って理由なんじゃないかと思ったけど。

**Comment by RyoNawa** [comment]
どちらか一方で十分→SVGはもうあるしJSは消せばいいや
で。

**Comment by masaha03** [comment]
つまりJSでの結果描画に特にメリットはないってことね。了解です。
